### PR TITLE
clear log button and show/hide volume checkbox added

### PR DESCRIPTION
**Pull request by k-lara**

### CODE REVIEW

**Comment by codeling** [comment]
In general, this looks very good 👍 , thanks for the contribution!

With the display of the volume, there are two issues (though in my opinion these are very minor and don't require immediate fixing):
* The 3D render window does not update automatically after the checkbox state change; one has to for example move the mouse into it to trigger the update. Fixing that is not straightforward unfortunately. It requires calling the `Render` method of the `vtkRenderWindow` that the volume is rendered in (which the iAVolumeRenderer does not have access to as far as I know). So either dlg_modalities or iAVolumeRenderer would need to get passed a pointer to the vtkRenderWindow they should update; or they would need to emit a signal which e.g. the mdichild listens to, and then calls that Render method.
* When a modality is selected and the "Edit" button right of the list is pressed, a dialog opens. There is also a "Main Renderer" checkbox in this dialog, that has the same functionality as the outside checkbox; but the two checkboxes are not synchronized. Ideally I guess the one in the dialog should be completely removed to avoid confusion.

**Comment by codeling** [comment]
In general, this looks very good 👍 , thanks for the contribution!

With the display of the volume, there are two issues (though in my opinion these are very minor and don't require immediate fixing):
* The 3D render window does not update automatically after the checkbox state change; one has to for example move the mouse into it to trigger the update. Fixing that is not straightforward unfortunately. It requires calling the `Render` method of the `vtkRenderWindow` that the volume is rendered in (which the iAVolumeRenderer does not have access to as far as I know). So either dlg_modalities or iAVolumeRenderer would need to get passed a pointer to the vtkRenderWindow they should update; or they would need to emit a signal which e.g. the mdichild listens to, and then calls that Render method.
* When a modality is selected and the "Edit" button right of the list is pressed, a dialog opens. There is also a "Main Renderer" checkbox in this dialog, that has the same functionality as the outside checkbox; but the two checkboxes are not synchronized. Ideally I guess the one in the dialog should be completely removed to avoid confusion.

**Comment by codeling** [comment]
In general, this looks very good 👍 , thanks for the contribution!

With the display of the volume, there are two issues (though in my opinion these are very minor and don't require immediate fixing):
* The 3D render window does not update automatically after the checkbox state change; one has to for example move the mouse into it to trigger the update. Fixing that is not straightforward unfortunately. It requires calling the `Render` method of the `vtkRenderWindow` that the volume is rendered in (which the iAVolumeRenderer does not have access to as far as I know). So either dlg_modalities or iAVolumeRenderer would need to get passed a pointer to the vtkRenderWindow they should update; or they would need to emit a signal which e.g. the mdichild listens to, and then calls that Render method.
* When a modality is selected and the "Edit" button right of the list is pressed, a dialog opens. There is also a "Main Renderer" checkbox in this dialog, that has the same functionality as the outside checkbox; but the two checkboxes are not synchronized. Ideally I guess the one in the dialog should be completely removed to avoid confusion.

**Comment by k-lara** [comment]
The updating should have been implemented but i think that i forgot to commit those changes, because I added this later on and did not commit anymore.

**Comment by codeling** [comment]
Then it should be just a matter of commiting and pushing, it should then automatically show up here.
Let me know if you need any assistance!

**Comment by codeling** [comment]
This seems to be a duplicate of the [other, already merged pull request to develop branch](https://github.com/3dct/open_iA/pull/4), closing.

**Pull request closed without merging**
